sudo: false
cache: bundler
language: ruby
rvm:
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-9.0.5.0
env:
  # this doesn't do anything for MRI or RBX, but it doesn't hurt them either
  # for JRuby, it enables us to get more accurate coverage data
  - JRUBY_OPTS="--debug"
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake
